import { personUserTable, companyUserTable } from "./users";
import {
  jobTypesTable,
  discoverySourcesTable,
  usedBeforeSourceTable,
} from "./onboarding";
import { plansTable } from "./plans";
import { projectsTable } from "./projects";
import { subscriptionsTable } from "./subscriptions";
import {
  agentsTable,
  agentTemplatesTable,
  serviceTypesTable,
  templateTypesTable,
} from "./agents";

// Import template schemas
import {
  // Minimal Template
  minimalTemplateIntroductionTable,
  minimalTemplateIntroductionPhotosTable,
  minimalTemplateAboutUsTable,
  minimalTemplateAboutUsTeamTable,
  minimalTemplateAboutUsMarqueeTable,
  minimalTemplateClientsTable,
  minimalTemplateClientsListTable,
  minimalTemplateExpertiseTable,
  minimalTemplateExpertiseTopicsTable,
  minimalTemplatePlansTable,
  minimalTemplatePlansListTable,
  minimalTemplatePlansIncludedItemsTable,
  minimalTemplateTermsConditionsTable,
  minimalTemplateTermsConditionsListTable,
  minimalTemplateFaqTable,
  minimalTemplateFaqListTable,
  minimalTemplateFooterTable,
  minimalTemplateFooterMarqueeTable,
} from "./templates/minimal";

import {
  // Flash Template
  flashTemplateIntroductionTable,
  flashTemplateIntroductionServicesTable,
  flashTemplateAboutUsTable,
  flashTemplateTeamTable,
  flashTemplateTeamMembersTable,
  flashTemplateExpertiseTable,
  flashTemplateExpertiseTopicsTable,
  flashTemplateResultsTable,
  flashTemplateResultsListTable,
  flashTemplateClientsTable,
  flashTemplateClientsListTable,
  flashTemplateStepsTable,
  flashTemplateStepsTopicsTable,
  flashTemplateStepsMarqueeTable,
  flashTemplateCtaTable,
  flashTemplateTestimonialsTable,
  flashTemplateTestimonialsListTable,
  flashTemplateInvestmentTable,
  flashTemplateDeliverablesTable,
  flashTemplateDeliverablesListTable,
  flashTemplatePlansTable,
  flashTemplatePlansListTable,
  flashTemplatePlansIncludedItemsTable,
  flashTemplateTermsConditionsTable,
  flashTemplateTermsConditionsListTable,
  flashTemplateFaqTable,
  flashTemplateFaqListTable,
  flashTemplateFooterTable,
  flashTemplateFooterMarqueeTable,
} from "./templates/flash";

import {
  // Prime Template
  primeTemplateIntroductionTable,
  primeTemplateIntroductionMarqueeTable,
  primeTemplateAboutUsTable,
  primeTemplateTeamTable,
  primeTemplateTeamMembersTable,
  primeTemplateExpertiseTable,
  primeTemplateExpertiseTopicsTable,
  primeTemplateResultsTable,
  primeTemplateResultsListTable,
  primeTemplateClientsTable,
  primeTemplateClientsListTable,
  primeTemplateCtaTable,
  primeTemplateStepsTable,
  primeTemplateStepsTopicsTable,
  primeTemplateTestimonialsTable,
  primeTemplateTestimonialsListTable,
  primeTemplateInvestmentTable,
  primeTemplateDeliverablesTable,
  primeTemplateDeliverablesListTable,
  primeTemplatePlansTable,
  primeTemplatePlansListTable,
  primeTemplatePlansIncludedItemsTable,
  primeTemplateTermsConditionsTable,
  primeTemplateTermsConditionsListTable,
  primeTemplateFaqTable,
  primeTemplateFaqListTable,
  primeTemplateFooterTable,
} from "./templates/prime";

export {
  personUserTable,
  companyUserTable,
  jobTypesTable,
  discoverySourcesTable,
  usedBeforeSourceTable,
  plansTable,
  projectsTable,
  subscriptionsTable,
  agentsTable,
  agentTemplatesTable,
  serviceTypesTable,
  templateTypesTable,
  // Minimal Template tables
  minimalTemplateIntroductionTable,
  minimalTemplateIntroductionPhotosTable,
  minimalTemplateAboutUsTable,
  minimalTemplateAboutUsTeamTable,
  minimalTemplateAboutUsMarqueeTable,
  minimalTemplateClientsTable,
  minimalTemplateClientsListTable,
  minimalTemplateExpertiseTable,
  minimalTemplateExpertiseTopicsTable,
  minimalTemplatePlansTable,
  minimalTemplatePlansListTable,
  minimalTemplatePlansIncludedItemsTable,
  minimalTemplateTermsConditionsTable,
  minimalTemplateTermsConditionsListTable,
  minimalTemplateFaqTable,
  minimalTemplateFaqListTable,
  minimalTemplateFooterTable,
  minimalTemplateFooterMarqueeTable,
  // Flash Template tables
  flashTemplateIntroductionTable,
  flashTemplateIntroductionServicesTable,
  flashTemplateAboutUsTable,
  flashTemplateTeamTable,
  flashTemplateTeamMembersTable,
  flashTemplateExpertiseTable,
  flashTemplateExpertiseTopicsTable,
  flashTemplateResultsTable,
  flashTemplateResultsListTable,
  flashTemplateClientsTable,
  flashTemplateClientsListTable,
  flashTemplateStepsTable,
  flashTemplateStepsTopicsTable,
  flashTemplateStepsMarqueeTable,
  flashTemplateCtaTable,
  flashTemplateTestimonialsTable,
  flashTemplateTestimonialsListTable,
  flashTemplateInvestmentTable,
  flashTemplateDeliverablesTable,
  flashTemplateDeliverablesListTable,
  flashTemplatePlansTable,
  flashTemplatePlansListTable,
  flashTemplatePlansIncludedItemsTable,
  flashTemplateTermsConditionsTable,
  flashTemplateTermsConditionsListTable,
  flashTemplateFaqTable,
  flashTemplateFaqListTable,
  flashTemplateFooterTable,
  flashTemplateFooterMarqueeTable,
  // Prime Template tables
  primeTemplateIntroductionTable,
  primeTemplateIntroductionMarqueeTable,
  primeTemplateAboutUsTable,
  primeTemplateTeamTable,
  primeTemplateTeamMembersTable,
  primeTemplateExpertiseTable,
  primeTemplateExpertiseTopicsTable,
  primeTemplateResultsTable,
  primeTemplateResultsListTable,
  primeTemplateClientsTable,
  primeTemplateClientsListTable,
  primeTemplateCtaTable,
  primeTemplateStepsTable,
  primeTemplateStepsTopicsTable,
  primeTemplateTestimonialsTable,
  primeTemplateTestimonialsListTable,
  primeTemplateInvestmentTable,
  primeTemplateDeliverablesTable,
  primeTemplateDeliverablesListTable,
  primeTemplatePlansTable,
  primeTemplatePlansListTable,
  primeTemplatePlansIncludedItemsTable,
  primeTemplateTermsConditionsTable,
  primeTemplateTermsConditionsListTable,
  primeTemplateFaqTable,
  primeTemplateFaqListTable,
  primeTemplateFooterTable,
};
