"use client";

import { useEffect, useRef } from "react";
import { toast, Slide } from "react-toastify";
import { useRouter } from "next/navigation";
import Link from "next/link";

import Logo from "#/components/icons/Logo";

import { SelectTemplate } from "#/modules/ai-generator/components/generation-steps";

import { useProjectGenerator } from "#/contexts/ProjectGeneratorContext";
import { useProposalGenerator } from "./ProposalGeneratorContext";
import { ServiceType } from "#/modules/ai-generator/components/generation-steps/ServiceType";
import type { TemplateType } from "#/types/project";
import { ClientInfo } from "#/modules/ai-generator/components/generation-steps/ClientInfo";
import { CompanyInfo } from "#/modules/ai-generator/components/generation-steps/CompanyInfo";
import { PricingStep } from "#/modules/ai-generator/components/generation-steps/PricingStep";
import { FinalStep } from "#/modules/ai-generator/components/generation-steps/FinalStep";
import { CustomTemplateFinalize } from "#/modules/ai-generator/components/generation-steps/CustomTemplateFinalize";
import { Loading } from "#/modules/ai-generator/components/loading/Loading";
import { Error as ErrorComponent } from "#/modules/ai-generator/components/error/error";
import CloseIcon from "#/components/icons/CloseIcon";
import {
  trackProposalCreationStarted,
  trackProposalAIGenerationRequested,
  trackProposalAIGenerationCompleted,
} from "#/lib/analytics/track";
import { PROJECT_SLUG_MAX_LENGTH } from "#/constants/project";
import { slugify, truncateSlug } from "#/lib/slug";

export default function NepfyAIPage() {
  const { templateType, formData, customTemplate } = useProjectGenerator();
  const {
    currentStep,
    setCurrentStep,
    selectedService,
    setSelectedService,
    clientName,
    setClientName,
    projectName,
    setProjectName,
    projectDescription,
    setProjectDescription,
    detailedClientInfo,
    setDetailedClientInfo,
    companyInfo,
    setCompanyInfo,
    selectedPlan,
    setSelectedPlan,
    originalPageUrl,
    setOriginalPageUrl,
    pagePassword,
    setPagePassword,
    validUntil,
    setValidUntil,
    userName,
    isLoading,
    setIsLoading,
    error,
    setError,
  } = useProposalGenerator();

  const router = useRouter();
  const generationStartTime = useRef<number | null>(null);
  const hasTrackedCreationStart = useRef(false);
  const autoGeneratedSlugRef = useRef<string | null>(null);

  // Track proposal creation started
  useEffect(() => {
    if (!hasTrackedCreationStart.current) {
      trackProposalCreationStarted({
        template_type: templateType || undefined,
      });
      hasTrackedCreationStart.current = true;
    }
  }, [templateType]);

  useEffect(() => {
    if (clientName && !originalPageUrl) {
      const suggestedSlug = truncateSlug(
        slugify(clientName),
        PROJECT_SLUG_MAX_LENGTH
      );
      if (suggestedSlug) {
        setOriginalPageUrl(suggestedSlug);
        autoGeneratedSlugRef.current = suggestedSlug;
      }
    }
  }, [clientName, originalPageUrl, setOriginalPageUrl]);
  const handleClientNameSubmit = (name: string) => {
    const suggestedSlug = truncateSlug(slugify(name), PROJECT_SLUG_MAX_LENGTH);
    if (!suggestedSlug) {
      return;
    }

    if (!originalPageUrl || originalPageUrl === autoGeneratedSlugRef.current) {
      setOriginalPageUrl(suggestedSlug);
      autoGeneratedSlugRef.current = suggestedSlug;
    }
  };

  const handleSlugEdited = () => {
    autoGeneratedSlugRef.current = null;
  };

  const handleServiceSelect = (serviceId: string) => {
    setSelectedService(serviceId);
  };

  const handleGenerateProposal = async () => {
    if (customTemplate) {
      if (
        !clientName ||
        !projectName ||
        !originalPageUrl ||
        !pagePassword ||
        !validUntil
      ) {
        return;
      }

      setIsLoading(true);
      try {
        const selectedColor =
          customTemplate.selectedColor ??
          customTemplate.mainColor ??
          customTemplate.templateData?.mainColor;
        const templateDataForRequest = {
          ...customTemplate.templateData,
          mainColor: selectedColor ?? customTemplate.templateData?.mainColor,
        };

        const response = await fetch("/api/projects/from-template", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            templateId: customTemplate.id,
            clientName,
            projectName,
            originalPageUrl,
            pagePassword,
            validUntil,
            templateData: templateDataForRequest,
            templateMainColor: templateDataForRequest.mainColor,
          }),
        });

        const result = await response.json();

        if (result.success) {
          const targetTemplateType =
            customTemplate.templateType ||
            (customTemplate.templateData?.templateType as TemplateType) ||
            "flash";
          router.push(
            `/editar?projectId=${result.data.id}&templateType=${targetTemplateType}`
          );
          return;
        }

        const errorMessage =
          typeof result.error === "string"
            ? result.error
            : "Erro ao criar proposta a partir do template";
        const error = new globalThis.Error(errorMessage);
        throw error;
      } catch (error: unknown) {
        const message =
          error instanceof globalThis.Error
            ? error.message
            : typeof error === "string"
              ? error
              : "Erro ao criar proposta a partir do template";
        toast.error(message, {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
          transition: Slide,
          className: "font-satoshi",
        });
      } finally {
        setIsLoading(false);
      }

      return;
    }

    if (
      !selectedService ||
      !clientName ||
      !projectName ||
      !projectDescription ||
      !originalPageUrl ||
      !pagePassword ||
      !validUntil
    ) {
      return;
    }

    setCurrentStep("final_step");

    // Track AI generation requested
    generationStartTime.current = Date.now();
    trackProposalAIGenerationRequested({
      template_type: templateType || "flash",
      project_name: projectName,
      selected_service: selectedService,
      include_terms: selectedPlan?.toString().includes("terms") || false,
      include_faq: selectedPlan?.toString().includes("faq") || false,
      selected_plans: selectedPlan || 1,
    });

    try {
      setIsLoading(true);
      const response = await fetch("/api/projects/ai-generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          selectedService,
          clientName,
          projectName,
          projectDescription,
          detailedClientInfo,
          companyInfo,
          selectedPlan,
          templateType,
          mainColor: formData.step1?.mainColor || null,
          originalPageUrl,
          pagePassword,
          validUntil,
        }),
      });

      const result = await response.json();

      if (result.success) {
        console.log("Proposal generated successfully:", result.data);

        // Calculate generation time
        const generationTimeSeconds = generationStartTime.current
          ? Math.round((Date.now() - generationStartTime.current) / 1000)
          : undefined;

        // Track AI generation completed
        trackProposalAIGenerationCompleted({
          template_type: templateType || "flash",
          project_id: result.data.project.id,
          project_name: projectName,
          generation_time_seconds: generationTimeSeconds,
          success: true,
        });
        setError(null);

        router.push(
          `/editar?projectId=${result.data.project.id}&templateType=${templateType}`
        );

        return;
      } else {
        console.error("Erro ao gerar proposta:", result.error);
        setError({
          message: result.error,
          details: result.details,
        });

        // Track failed generation
        trackProposalAIGenerationCompleted({
          template_type: templateType || "flash",
          project_id: "",
          project_name: projectName,
          generation_time_seconds: generationStartTime.current
            ? Math.round((Date.now() - generationStartTime.current) / 1000)
            : undefined,
          success: false,
          error: result.error || "Unknown error",
        });

        toast.error("Erro ao gerar proposta: " + result.error, {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
          transition: Slide,
          className: "font-satoshi",
        });
      }
    } catch (error: unknown) {
      console.error("Error generating proposal:", error);

      toast.error("Erro ao gerar proposta. Tente novamente.", {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: true,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Slide,
        className: "font-satoshi",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const finalStepBack = customTemplate
    ? () => setCurrentStep("template_selection")
    : () => setCurrentStep("pricing_step");

  if (error) {
    return (
      <div className="flex h-full w-full items-center justify-center p-7">
        <ErrorComponent
          error={error}
          handleRetry={handleGenerateProposal}
          handleExit={() => router.push("/dashboard")}
          isLoading={isLoading}
        />
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="flex h-full w-full items-center justify-center p-7">
        <Loading />
      </div>
    );
  }

  return (
    <>
      <nav className="border-b-white-neutral-light-300 bg-white-neutral-light-200 flex items-center justify-between border-b p-7">
        <div className="flex items-center gap-2">
          <Logo fill="#1C1A22" />

          <p
            className="border-white-neutral-light-300 rounded-2xs bg-white-neutral-light-200 hidden border px-2 py-1 text-xs sm:block sm:text-[16px]"
            style={{
              backgroundImage: `repeating-linear-gradient(
                    45deg,
                    rgba(0,0,0,0.1) 0px,
                    rgba(0,0,0,0.1) 1px,
                    transparent 1px,
                    transparent 3px
                  )`,
            }}
          >
            Gerador de Proposta
          </p>
        </div>

        <div className="flex items-center gap-1 sm:gap-2">
          {/* <SaveDraftButton
            clientName={clientName}
            projectName={projectName}
            projectDescription={projectDescription}
            companyInfo={companyInfo}
          /> */}
          <Link
            href="/dashboard"
            className="border-white-neutral-light-300 hover:bg-white-neutral-light-200 bg-white-neutral-light-100 button-inner flex h-[40px] w-[40px] cursor-pointer items-center justify-center rounded-[10px] border sm:h-[44px] sm:w-[44px]"
          >
            <CloseIcon width="10" height="10" fill="#1C1A22" />
          </Link>
        </div>
      </nav>
      <div className="h-full">
        <div className="mx-auto h-full p-6">
          {(() => {
            const stepMap: Record<string, React.ReactNode> = {
              template_selection: (
                <div>
                  <SelectTemplate
                    handleNextStep={() => setCurrentStep("service_selection")}
                  />
                </div>
              ),
              service_selection: (
                <ServiceType
                  onServiceSelect={handleServiceSelect}
                  selectedService={selectedService}
                  handleBack={() => setCurrentStep("template_selection")}
                  handleNext={() => setCurrentStep("company_info")}
                />
              ),
              company_info: (
                <CompanyInfo
                  companyInfo={companyInfo}
                  setCompanyInfo={setCompanyInfo}
                  handleBack={() => setCurrentStep("service_selection")}
                  handleNext={() => setCurrentStep("client_details")}
                />
              ),
              client_details: (
                <ClientInfo
                  clientData={{
                    clientName,
                    projectName,
                    detailedClientInfo,
                    projectDescription,
                  }}
                  setClientData={({
                    clientName,
                    projectName,
                    projectDescription,
                    detailedClientInfo,
                  }) => {
                    setClientName(clientName);
                    setProjectName(projectName);
                    setProjectDescription(projectDescription);
                    setDetailedClientInfo(detailedClientInfo || "");
                  }}
                  onClientNameSubmit={handleClientNameSubmit}
                  handleBack={() => setCurrentStep("company_info")}
                  handleNext={() => setCurrentStep("pricing_step")}
                />
              ),
              pricing_step: (
                <PricingStep
                  selectedPlan={selectedPlan || 1}
                  handlePlanSelect={setSelectedPlan}
                  handleBack={() => setCurrentStep("client_details")}
                  handleNext={() => setCurrentStep("final_step")}
                />
              ),
              custom_template_finalize: (
                <CustomTemplateFinalize
                  handleGenerateProposal={handleGenerateProposal}
                  handleBack={() => setCurrentStep("template_selection")}
                  userName={userName}
                  step={currentStep}
                  clientName={clientName}
                  setClientName={setClientName}
                  projectName={projectName}
                  setProjectName={setProjectName}
                  originalPageUrl={originalPageUrl}
                  setOriginalPageUrl={setOriginalPageUrl}
                  pagePassword={pagePassword}
                  setPagePassword={setPagePassword}
                  validUntil={validUntil}
                  setValidUntil={setValidUntil}
                  onSlugEdited={handleSlugEdited}
                />
              ),
              final_step: (
                <FinalStep
                  handleGenerateProposal={handleGenerateProposal}
                  handleBack={finalStepBack}
                  userName={userName}
                  step={currentStep}
                  clientName={clientName}
                  setClientName={setClientName}
                  projectName={projectName}
                  setProjectName={setProjectName}
                  originalPageUrl={originalPageUrl}
                  setOriginalPageUrl={setOriginalPageUrl}
                  pagePassword={pagePassword}
                  setPagePassword={setPagePassword}
                  validUntil={validUntil}
                  setValidUntil={setValidUntil}
                  onSlugEdited={handleSlugEdited}
                  isCustomTemplateFlow={Boolean(customTemplate)}
                />
              ),
            };
            return stepMap[currentStep] || null;
          })()}
        </div>
      </div>
    </>
  );
}
