ALTER TABLE "projects"
ALTER COLUMN "id" DROP IDENTITY IF EXISTS;

ALTER TABLE "projects"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "projects"
ALTER COLUMN "id" SET DATA TYPE uuid USING "id"::uuid;

ALTER TABLE "projects"
ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

