ALTER TABLE "projects" DROP COLUMN "hide_client_name";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "client_name";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_client_photo";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "client_photo";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "company_name";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "company_email";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "cta_button_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "page_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "page_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_page_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "services";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_services";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_about_us_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_about_us_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_about_us_subtitle_1";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_about_us_subtitle_2";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "about_us_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "about_us_subtitle_1";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "about_us_subtitle_2";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_about_your_team_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "our_team_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_expertise_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "expertise_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_results_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "results_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_clients_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "client_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_process_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_process_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "process_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_cta_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "cta_background_image";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_testimonials_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_investment_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "investment_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_included_services_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_plans_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_terms_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_faq_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_faq_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "faq_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_final_message_section";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "hide_final_message_subtitle";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "end_message_title";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "end_message_title_2";--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "end_message_description";