-- Drop legacy "flash" template tables
DROP TABLE IF EXISTS
  "flash_template_testimonials_list",
  "flash_template_testimonials",
  "flash_template_terms_conditions_list",
  "flash_template_terms_conditions",
  "flash_template_team_members",
  "flash_template_team",
  "flash_template_steps_topics",
  "flash_template_steps_marquee",
  "flash_template_steps",
  "flash_template_results_list",
  "flash_template_results",
  "flash_template_plans_included_items",
  "flash_template_plans_list",
  "flash_template_plans",
  "flash_template_investment",
  "flash_template_introduction_services",
  "flash_template_introduction",
  "flash_template_footer_marquee",
  "flash_template_footer",
  "flash_template_faq_list",
  "flash_template_faq",
  "flash_template_expertise_topics",
  "flash_template_expertise",
  "flash_template_deliverables_list",
  "flash_template_deliverables",
  "flash_template_cta",
  "flash_template_clients_list",
  "flash_template_clients",
  "flash_template_about_us"
CASCADE;

-- Drop legacy "minimal" template tables
DROP TABLE IF EXISTS
  "minimal_template_terms_conditions_list",
  "minimal_template_terms_conditions",
  "minimal_template_plans_included_items",
  "minimal_template_plans_list",
  "minimal_template_plans",
  "minimal_template_introduction_photos",
  "minimal_template_introduction",
  "minimal_template_footer_marquee",
  "minimal_template_footer",
  "minimal_template_faq_list",
  "minimal_template_faq",
  "minimal_template_expertise_topics",
  "minimal_template_expertise",
  "minimal_template_clients_list",
  "minimal_template_clients",
  "minimal_template_about_us_team",
  "minimal_template_about_us_marquee",
  "minimal_template_about_us"
CASCADE;

-- Drop legacy "prime" template tables
DROP TABLE IF EXISTS
  "prime_template_testimonials_list",
  "prime_template_testimonials",
  "prime_template_terms_conditions_list",
  "prime_template_terms_conditions",
  "prime_template_team_members",
  "prime_template_team",
  "prime_template_steps_topics",
  "prime_template_steps",
  "prime_template_results_list",
  "prime_template_results",
  "prime_template_plans_included_items",
  "prime_template_plans_list",
  "prime_template_plans",
  "prime_template_investment",
  "prime_template_introduction_marquee",
  "prime_template_introduction",
  "prime_template_footer",
  "prime_template_faq_list",
  "prime_template_faq",
  "prime_template_expertise_topics",
  "prime_template_expertise",
  "prime_template_deliverables_list",
  "prime_template_deliverables",
  "prime_template_cta",
  "prime_template_clients_list",
  "prime_template_clients",
  "prime_template_about_us"
CASCADE;

